const questions: Array<MixedQuestionType> = [
  {
    ev_nominatief: 'αἷμα',
    ev_accusatief: 'αἷμα',
    ev_genitief: 'αἷματος',
    ev_datief: 'αἷματι',
    mv_nominatief: 'αἷματα',
    mv_accusatief: 'αἷματα',
    mv_genitief: 'αἷματων',
    mv_datief: 'αἷμασιν',
    vocabularyAnswers: ['bloed'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'βάπτισμα',
    ev_accusatief: 'βάπτισμα',
    ev_genitief: 'βάπτισματος',
    ev_datief: 'βάπτισματι',
    mv_nominatief: 'βάπτισματα',
    mv_accusatief: 'βάπτισματα',
    mv_genitief: 'βάπτισματων',
    mv_datief: 'βάπτισμασιν',
    vocabularyAnswers: ['doopsel'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'θέλημα',
    ev_accusatief: 'θέλημα',
    ev_genitief: 'θέληματος',
    ev_datief: 'θέληματι',
    mv_nominatief: 'θέληματα',
    mv_accusatief: 'θέληματα',
    mv_genitief: 'θέληματων',
    mv_datief: 'θέλημασιν',
    vocabularyAnswers: ['wil'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'κρῖμα',
    ev_accusatief: 'κρῖμα',
    ev_genitief: 'κρῖματος',
    ev_datief: 'κρῖματι',
    mv_nominatief: 'κρῖματα',
    mv_accusatief: 'κρῖματα',
    mv_genitief: 'κρῖματων',
    mv_datief: 'κρῖμασιν',
    vocabularyAnswers: ['oordeel'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'ὄνομα',
    ev_accusatief: 'ὄνομα',
    ev_genitief: 'ὄνοματος',
    ev_datief: 'ὄνοματι',
    mv_nominatief: 'ὄνοματα',
    mv_accusatief: 'ὄνοματα',
    mv_genitief: 'ὄνοματων',
    mv_datief: 'ὄνομασιν',
    vocabularyAnswers: ['naam'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'πνεῦμα',
    ev_accusatief: 'πνεῦμα',
    ev_genitief: 'πνεῦματος',
    ev_datief: 'πνεῦματι',
    mv_nominatief: 'πνεῦματα',
    mv_accusatief: 'πνεῦματα',
    mv_genitief: 'πνεῦματων',
    mv_datief: 'πνεῦμασιν',
    vocabularyAnswers: ['geest'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'ῥῆμα',
    ev_accusatief: 'ῥῆμα',
    ev_genitief: 'ῥῆματος',
    ev_datief: 'ῥῆματι',
    mv_nominatief: 'ῥῆματα',
    mv_accusatief: 'ῥῆματα',
    mv_genitief: 'ῥῆματων',
    mv_datief: 'ῥῆμασιν',
    vocabularyAnswers: ['woord'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'σπέρμα',
    ev_accusatief: 'σπέρμα',
    ev_genitief: 'σπέρματος',
    ev_datief: 'σπέρματι',
    mv_nominatief: 'σπέρματα',
    mv_accusatief: 'σπέρματα',
    mv_genitief: 'σπέρματων',
    mv_datief: 'σπέρμασιν',
    vocabularyAnswers: ['zaad'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'στόμα',
    ev_accusatief: 'στόμα',
    ev_genitief: 'στόματος',
    ev_datief: 'στόματι',
    mv_nominatief: 'στόματα',
    mv_accusatief: 'στόματα',
    mv_genitief: 'στόματων',
    mv_datief: 'στόμασιν',
    vocabularyAnswers: ['mond'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'σῶμα',
    ev_accusatief: 'σῶμα',
    ev_genitief: 'σῶματος',
    ev_datief: 'σῶματι',
    mv_nominatief: 'σῶματα',
    mv_accusatief: 'σῶματα',
    mv_genitief: 'σῶματων',
    mv_datief: 'σῶμασιν',
    vocabularyAnswers: ['lichaam'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'οὖς',
    ev_accusatief: 'οὖς',
    ev_genitief: 'ὠτός',
    ev_datief: 'ὠτί',
    mv_nominatief: 'ὦτα',
    mv_accusatief: 'ὦτα',
    mv_genitief: 'ὤτων',
    mv_datief: 'ὠσίν',
    vocabularyAnswers: ['oor'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'πῦρ',
    ev_accusatief: 'πῦρ',
    ev_genitief: 'πυρός',
    ev_datief: 'πυρί',
    mv_nominatief: 'πυρα',
    mv_accusatief: 'πυρα',
    mv_genitief: 'πυρων',
    mv_datief: 'πυρσίν',
    vocabularyAnswers: ['vuur'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'τέρας',
    ev_accusatief: 'τέρας',
    ev_genitief: 'τέρατος',
    ev_datief: 'τέρατί',
    mv_nominatief: 'τέρατα',
    mv_accusatief: 'τέρατα',
    mv_genitief: 'τέρατων',
    mv_datief: 'τέρασίν',
    vocabularyAnswers: ['wonder'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'ὕδωρ',
    ev_accusatief: 'ὕδωρ',
    ev_genitief: 'ὕδατος',
    ev_datief: 'ὕδατί',
    mv_nominatief: 'ὕδατα',
    mv_accusatief: 'ὕδατα',
    mv_genitief: 'ὕδατων',
    mv_datief: 'ὕδασιν',
    vocabularyAnswers: ['water'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'φῶς',
    ev_accusatief: 'φῶς',
    ev_genitief: 'φωτός',
    ev_datief: 'φωτί',
    mv_nominatief: 'φωτα',
    mv_accusatief: 'φωτα',
    mv_genitief: 'φωτων',
    mv_datief: 'φωσιν',
    vocabularyAnswers: ['licht'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'γένος',
    ev_accusatief: 'γένος',
    ev_genitief: 'γένους',
    ev_datief: 'γένει',
    mv_nominatief: 'γένη',
    mv_accusatief: 'γένη',
    mv_genitief: 'γένῶν',
    mv_datief: 'γένεσιν',
    vocabularyAnswers: ['ras', 'geslacht', 'aard'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'ἔθνος',
    ev_accusatief: 'ἔθνος',
    ev_genitief: 'ἔθνους',
    ev_datief: 'ἔθνει',
    mv_nominatief: 'ἔθνη',
    mv_accusatief: 'ἔθνη',
    mv_genitief: 'ἔθνῶν',
    mv_datief: 'ἔθνεσιν',
    vocabularyAnswers: ['natie', 'volk'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'ἔλεος',
    ev_accusatief: 'ἔλεος',
    ev_genitief: 'ἔλεους',
    ev_datief: 'ἔλεει',
    mv_nominatief: 'ἔλεη',
    mv_accusatief: 'ἔλεη',
    mv_genitief: 'ἔλεῶν',
    mv_datief: 'ἔλεεσιν',
    vocabularyAnswers: ['ontferming', 'medelijden'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'ἔτος',
    ev_accusatief: 'ἔτος',
    ev_genitief: 'ἔτους',
    ev_datief: 'ἔτει',
    mv_nominatief: 'ἔτη',
    mv_accusatief: 'ἔτη',
    mv_genitief: 'ἔτῶν',
    mv_datief: 'ἔτεσιν',
    vocabularyAnswers: ['jaar'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'μέλος',
    ev_accusatief: 'μέλος',
    ev_genitief: 'μέλους',
    ev_datief: 'μέλει',
    mv_nominatief: 'μέλη',
    mv_accusatief: 'μέλη',
    mv_genitief: 'μέλῶν',
    mv_datief: 'μέλεσιν',
    vocabularyAnswers: ['lid'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'μέρος',
    ev_accusatief: 'μέρος',
    ev_genitief: 'μέρους',
    ev_datief: 'μέρει',
    mv_nominatief: 'μέρη',
    mv_accusatief: 'μέρη',
    mv_genitief: 'μέρῶν',
    mv_datief: 'μέρεσιν',
    vocabularyAnswers: ['deel'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'ὄρος',
    ev_accusatief: 'ὄρος',
    ev_genitief: 'ὄρους',
    ev_datief: 'ὄρει',
    mv_nominatief: 'ὄρη',
    mv_accusatief: 'ὄρη',
    mv_genitief: 'ὄρῶν',
    mv_datief: 'ὄρεσιν',
    vocabularyAnswers: ['berg'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'πλῆθος',
    ev_accusatief: 'πλῆθος',
    ev_genitief: 'πλῆθους',
    ev_datief: 'πλῆθει',
    mv_nominatief: 'πλῆθη',
    mv_accusatief: 'πλῆθη',
    mv_genitief: 'πλῆθῶν',
    mv_datief: 'πλῆθεσιν',
    vocabularyAnswers: ['massa'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'σκεῦος',
    ev_accusatief: 'σκεῦος',
    ev_genitief: 'σκεῦους',
    ev_datief: 'σκεῦει',
    mv_nominatief: 'σκεῦη',
    mv_accusatief: 'σκεῦη',
    mv_genitief: 'σκεῦῶν',
    mv_datief: 'σκεῦεσιν',
    vocabularyAnswers: ['vat'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'σκότος',
    ev_accusatief: 'σκότος',
    ev_genitief: 'σκότους',
    ev_datief: 'σκότει',
    mv_nominatief: 'σκότη',
    mv_accusatief: 'σκότη',
    mv_genitief: 'σκότῶν',
    mv_datief: 'σκότεσιν',
    vocabularyAnswers: ['duisternis'],
    type: 'vervoeging-woordenschat'
  },
  {
    ev_nominatief: 'τέλος',
    ev_accusatief: 'τέλος',
    ev_genitief: 'τέλους',
    ev_datief: 'τέλει',
    mv_nominatief: 'τέλη',
    mv_accusatief: 'τέλη',
    mv_genitief: 'τέλῶν',
    mv_datief: 'τέλεσιν',
    vocabularyAnswers: ['einde'],
    type: 'vervoeging-woordenschat'
  }
]

const lesson29ConjugationsWithVocabulary: LessonType = {
  id: 'lesson29-conjugations-with-vocabulary',
  name: 'Les 29 – Vervoegingen met woordenschat',
  type: 'vervoeging-woordenschat',
  active: false,
  questions
}
export default lesson29ConjugationsWithVocabulary
